### ISSUE TITLE
Замечания по блоку "Льготные кредиты на инвестиционные цели для субъектов МСП"

### ISSUE THREAD

**Issue by testario** [VaniaFed/landing-vue#7]
1. Семантическая ошибка: использование тега header в контенте в качестве заголовка. Header на странице всегда один и должен размещать в себе навигацию по странице | сайту, в контенте нужно использовать теги группы h1-h6. 
<img width="805" alt="изображение" src="https://github.com/VaniaFed/landing-vue/assets/52890557/018f83c2-915f-4aa3-8685-e80032898914">

_Примечание:_ h1 тоже должен быть один на странице и всегда сверху, так как по нему ориентируются поисковики (SEO оптимизация)

2. Не верно сверстан блок
Макет:
<img width="687" alt="изображение" src="https://github.com/VaniaFed/landing-vue/assets/52890557/bb0cd2ed-3983-4af4-9541-84354ee36e83">

Верстка:
<img width="1336" alt="изображение" src="https://github.com/VaniaFed/landing-vue/assets/52890557/843a37f3-0872-4f4a-8aa8-4fef25551e2d">

Необходимо пересмотреть этот момент и сделать по другому.

3. Семантическая ошибка: использование тега p в качестве структурного блока. Тег p создан для обозначения абзаца, его использование правильно только в тексте. В случаях, где нужно сделать что то, как на макете, лучше использовать div
<img width="949" alt="изображение" src="https://github.com/VaniaFed/landing-vue/assets/52890557/5ff6991c-ab5e-4a26-b38b-c9be4d07344a">

<img width="838" alt="изображение" src="https://github.com/VaniaFed/landing-vue/assets/52890557/cc60df25-7500-41a0-a5b1-935ac2f3e6ef">

4. Семантическая ошибка: та же история, что и в предыдущем блоке, заголовки в местах, для них не предназначенных. 
<img width="656" alt="изображение" src="https://github.com/VaniaFed/landing-vue/assets/52890557/d6e4d2db-da3d-4de5-a7c9-7dfcea1f0386">

### Планшет
Посмотреть адаптив до 768, верстка не обработана
<img width="805" alt="изображение" src="https://github.com/VaniaFed/landing-vue/assets/52890557/616d9e97-3dd7-4ae6-ab03-43305fe87622">

### Мобилка

<img width="865" alt="изображение" src="https://github.com/VaniaFed/landing-vue/assets/52890557/a3ad8c7f-c913-45f8-a8ac-457c094b2866">

**Comment by VaniaFed** [comment]
Паш, насколько мне известно, и насколько мне удалось погуглить, теги header и footer могут встречаться на странице несколько раз, ссылки:

https://htmlacademy.ru/blog/html/semantics
https://doka.guide/html/header/

![изображение](https://github.com/VaniaFed/landing-vue/assets/24530480/62828668-4315-4762-8f74-c46cc37bf3c8)

**Comment by VaniaFed** [comment]
В данном случае header используется как вводная часть секции, без которой можно было бы обойтись, если бы не эта секция. 
![изображение](https://github.com/VaniaFed/landing-vue/assets/24530480/b030823e-24eb-4958-a674-9ebf73b87446)

**Comment by VaniaFed** [comment]
Во втором пункте у меня на всех ключевых viewport'ах все хорошо ложится
![изображение](https://github.com/VaniaFed/landing-vue/assets/24530480/9e26f86b-76bf-421e-a9d8-e770af0b3f2c)

@testario 
Возможно, дизайнер успел внести изменения в макет.
У меня есть более старая копия макета, давай на ней лучше смотреть:
https://www.figma.com/file/pHjMs7sdq6Ykn0e2lq4lSn/_NEW--Client-%2F-Investments-(Copy)-(Copy)?type=design&node-id=717%3A12074&mode=dev&t=ZhnTKeLvhVwvFxuV-1

**Comment by testario** [comment]
> Паш, насколько мне известно, и насколько мне удалось погуглить, теги header и footer могут встречаться на странице несколько раз, ссылки:
> 
> https://htmlacademy.ru/blog/html/semantics https://doka.guide/html/header/
> 
> ![изображение](https://private-user-images.githubusercontent.com/24530480/313636511-62828668-4315-4762-8f74-c46cc37bf3c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjQ0ODAsIm5iZiI6MTcxMDc2NDE4MCwicGF0aCI6Ii8yNDUzMDQ4MC8zMTM2MzY1MTEtNjI4Mjg2NjgtNDMxNS00NzYyLThmNzQtYzQ2Y2MzN2JmM2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDEyMTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZDA2NjRlZGVhMmE1NmMyYTU1YzQ5NGZjNGMyMzRjNWZhYmViMWI1YzRkMDY3YzkxNTFiZjliNzVlMDA4ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W3RcOwGEdhzp4HQ3TW122KA_J5-YynmWJ0NYhwgJQFE)

Желательно, чтобы он был один. Так можно очень удобно отделить навигацию сайта, всякие элементы типа поиска, логотипов и прочего. В целом, можешь не фиксить, если на html-academy пишут, что можно, значит скорее всего они правы. Я просто не привык видеть этот тег где то, кроме шапки сайта

**Comment by testario** [comment]
> Во втором пункте у меня на всех ключевых viewport'ах все хорошо ложится ![изображение](https://private-user-images.githubusercontent.com/24530480/313638720-9e26f86b-76bf-421e-a9d8-e770af0b3f2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjQ3NTgsIm5iZiI6MTcxMDc2NDQ1OCwicGF0aCI6Ii8yNDUzMDQ4MC8zMTM2Mzg3MjAtOWUyNmY4NmItNzZiZi00MjFlLWE5ZDgtZTc3MGFmMGIzZjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDEyMjA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNzhhYmNjMjU0M2FhZmY3OTAzMjk2NmY1MTRlNjQwYjZjOTRjZWUxOTE2YjMyZjJmMjc1Y2EzNWYzNmVlNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iRIGvE0TNXBFWvEVzETlRdlyo5UV9rrHplBzucC57js)
> 
> @testario Возможно, дизайнер успел внести изменения в макет. У меня есть более старая копия макета, давай на ней лучше смотреть: https://www.figma.com/file/pHjMs7sdq6Ykn0e2lq4lSn/_NEW--Client-%2F-Investments-(Copy)-(Copy)?type=design&node-id=717%3A12074&mode=dev&t=ZhnTKeLvhVwvFxuV-1

на планшете да, так, на десктопе они в одной строке

**Comment by VaniaFed** [comment]
> строке

у меня на одной строке
с какого браузера у тебя так?
![изображение](https://github.com/VaniaFed/landing-vue/assets/24530480/42109bf9-83bb-4fdf-9be4-2b9567a585bf)
